"""Changed VoteBase Identifier

Revision ID: 742746872d7f
Revises: c79f33a93b82
Create Date: 2025-08-17 16:37:27.728491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '742746872d7f'
down_revision: Union[str, Sequence[str], None] = 'c79f33a93b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_actor_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['student_id'])
    op.drop_column('audit_logs', 'ip_address')
    op.add_column('candidates', sa.Column('is_contesting', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('candidates', sa.Column('candidate_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_candidates_user_id'), 'candidates', type_='unique')
    op.create_unique_constraint('uq_candidate_user_election', 'candidates', ['user_id', 'election_id'])
    op.drop_constraint(op.f('candidates_user_id_fkey'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['student_id'])
    op.drop_column('candidates', 'id')
    op.drop_constraint(op.f('elections_created_by_fkey'), 'elections', type_='foreignkey')
    op.create_foreign_key(None, 'elections', 'users', ['created_by'], ['student_id'])
    op.alter_column('users', 'student_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'salt')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'id')
    op.drop_column('users', 'updated_at')
    op.add_column('votes', sa.Column('student_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('votes_voter_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_candidate_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['student_id'], ['student_id'])
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['candidate_id'])
    op.drop_column('votes', 'voter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('voter_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_candidate_id_fkey'), 'votes', 'candidates', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('votes_voter_id_fkey'), 'votes', 'users', ['voter_id'], ['id'])
    op.drop_column('votes', 'student_id')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('salt', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.alter_column('users', 'student_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'elections', type_='foreignkey')
    op.create_foreign_key(op.f('elections_created_by_fkey'), 'elections', 'users', ['created_by'], ['id'])
    op.add_column('candidates', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_user_id_fkey'), 'candidates', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_candidate_user_election', 'candidates', type_='unique')
    op.create_unique_constraint(op.f('uq_candidates_user_id'), 'candidates', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('candidates', 'candidate_id')
    op.drop_column('candidates', 'is_contesting')
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_actor_id_fkey'), 'audit_logs', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###
