"""Added updated_at to vote model

Revision ID: c79f33a93b82
Revises: 0003_candidate_details
Create Date: 2025-08-16 14:57:53.019727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c79f33a93b82'
down_revision: Union[str, Sequence[str], None] = '0003_candidate_details'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_column('audit_logs', 'extra_data')
    op.drop_index(op.f('ix_candidates_election_id'), table_name='candidates')
    op.alter_column('users', 'student_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.add_column('votes', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('votes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_votes_candidate_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_election_id'), table_name='votes')
    op.drop_constraint(op.f('uq_votes_election_voter'), 'votes', type_='unique')
    op.drop_column('votes', 'extra_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_votes_election_voter'), 'votes', ['election_id', 'voter_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_votes_election_id'), 'votes', ['election_id'], unique=False)
    op.create_index(op.f('ix_votes_candidate_id'), 'votes', ['candidate_id'], unique=False)
    op.drop_column('votes', 'updated_at')
    op.drop_column('votes', 'metadata')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.alter_column('users', 'student_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_candidates_election_id'), 'candidates', ['election_id'], unique=False)
    op.add_column('audit_logs', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.drop_column('audit_logs', 'metadata')
    # ### end Alembic commands ###
